### ISSUE TITLE
123

### ISSUE THREAD

**Issue by saber-yy** [saberShenFeng/ZYswitch#1]

**Comment by saberShenFeng** [comment]
> thanks , I have set /setprivacy to disable , but the function still can not listen the message from other bots.

`bot.onText(/123/, (msg) => {
let chatId = msg.chat.id;
let messageId = msg.message_id;

console.log('did receive listen msg->'+JSON.stringify(msg,null,100));

bot.sendMessage(chatId,'bot did receive your message ');

setTimeout(function () {

    let deleteMessageId = messageId + 1;
    bot.deleteMessage(chatId,deleteMessageId).then(msg=>{

        console.log('deleteResult:',msg);
    }).catch(error=>console.log(error));
},1000 * 5);
});`
I write this function and it works ,can delete message from rebot,but in fact, due to the network delay, the messageId of the reply does not necessarily increase by 1. so ..you know ,this question is depending on whether i can get the messageId of other rebots reply to？

**Comment by saberShenFeng** [comment]
`
bot.onText(/123/, (msg) => {
    let chatId = msg.chat.id;
    let messageId = msg.message_id;

    console.log('did receive listen msg->'+JSON.stringify(msg,null,100));

    bot.sendMessage(chatId,'bot did receive your message ');

    setTimeout(function () {

        let deleteMessageId = messageId + 1;
        bot.deleteMessage(chatId,deleteMessageId).then(msg=>{

            console.log('deleteResult:',msg);
        }).catch(error=>console.log(error));
    },1000 * 5);
});
`

**Comment by saberShenFeng** [comment]
`
       bot.onText(/123/, (msg) => {
       let chatId = msg.chat.id;
       let messageId = msg.message_id;

      console.log('did receive listen msg->'+JSON.stringify(msg,null,100));

    bot.sendMessage(chatId,'bot did receive your message ');

       setTimeout(function () {

        let deleteMessageId = messageId + 1;
        bot.deleteMessage(chatId,deleteMessageId).then(msg=>{

            console.log('deleteResult:',msg);
        }).catch(error=>console.log(error));
    },1000 * 5);
    });
`

**Comment by saberShenFeng** [comment]
bot.onText(/123/, (msg) => {
    let chatId = msg.chat.id;
    let messageId = msg.message_id;

    console.log('did receive listen msg->'+JSON.stringify(msg,null,100));

    bot.sendMessage(chatId,'bot did receive your message ');

    setTimeout(function () {

        let deleteMessageId = messageId + 1;
        bot.deleteMessage(chatId,deleteMessageId).then(msg=>{

            console.log('deleteResult:',msg);
        }).catch(error=>console.log(error));
    },1000 * 5);
    });
